version: "3"

services:
  kafka:
        restart: always
        image: ubuntu/kafka
        entrypoint: >
            bash -c "export CLUSTER_ID=$$(/opt/kafka/bin/kafka-storage.sh random-uuid) &&
            /opt/kafka/bin/kafka-storage.sh format --cluster-id $$CLUSTER_ID --config /etc/kafka/kraft/server.properties &&
            /opt/kafka/bin/kafka-server-start.sh /etc/kafka/kraft/server.properties 
              --override advertised.listeners=$$ADVERTISED_LISTENERS 
              --override listener.security.protocol.map=$$PROTOCOL_MAP
              --override listeners=$$LISTENERS"
        ports:
            - "9092:9092"
        environment:
            ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 256M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/migrations.txt:/migrations.txt"
    ports:
      - "9042:9042"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 256M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

networks:
  web:
    driver: bridge
